version: 1

formatters:
  simple:
    format: "%(levelname)-7s %(name)2s.%(funcName)10s(): %(message)s"
    datefmt: '%d/%m/%Y %H:%M:%S'
  extended:
    format: "%(asctime)s %(levelname)7s %(name)s.%(funcName)s(): %(message)s"
    datefmt: '%d/%m/%Y %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple

  file_handler:
    class: logging.FileHandler
    filename: ../tmp/test.log
    mode: w
    formatter: extended
#    propagate: false

loggers:
  dev:
    level: WARNING
    handlers: [console, file_handler]
    propagate: False
  sub:
    handlers: [console, file_handler]
    level: DEBUG
root:
  handlers: # [file_handler]
