version: 1

formatters:
  simple:
    format: "%(levelname)-7s %(name)2s.%(funcName)10s(): %(message)s"
    datefmt: '%d/%m/%Y %H:%M:%S'
  extended:
    format: "%(asctime)s %(levelname)7s %(filename)10s %(lineno)4d %(name)s.%(funcName)s(): %(message)s"
    datefmt: '%d/%m/%Y %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple

  file_handler:
    class: logging.FileHandler
    filename: ../tmp/test.log
    mode: w
    formatter: extended
#    propagate: false

loggers:
  my_utils:
    level: WARNING
    handlers: [console, file_handler]
    propagate: False
  metering:
    level: WARNING
    handlers: [console, file_handler]
    propagate: False
  qr_read:
    level: WARNING
    handlers: [console, file_handler]
    propagate: False
  __main__:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: False

root:
  handlers: # [file_handler]
