version: 1

formatters:
  simple:
    format: "%(levelname)-7s %(funcName)10s(): %(message)s"
    datefmt: '%d/%m/%Y %H:%M:%S'
  extended:
    format: "%(asctime)s %(levelname)7s %(filename)10s %(lineno)4d %(name)s.%(funcName)s(): %(message)s"
    datefmt: '%d/%m/%Y %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple

  file_handler:
    class: logging.FileHandler
    filename: ../tmp/test.log
    mode: w
    formatter: extended

loggers:
  thermo:
    level: WARNING # INFO #
    handlers: [console, file_handler]

#  thermo.my_utils:
#    level: INFO # WARNING #
  thermo.metering:
    level:  INFO # WARNING #
#  thermo.qr_read:
#    level: DEBUG # INFO # WARNING #
#  thermo.db:
#    level: DEBUG # WARNING #
#  thermo.chart:
#    level: DEBUG # WARNING #
  thermo.analyzer:
    level: INFO # WARNING #
#  thermo.__main__:
#    level: INFO # WARNING #

root:
  handlers:
